name: BungeeMaster
main: me.tonymaster21.bungeemaster.spigot.BungeeMaster
version: @VERSION@
author: TonyMaster21
description: ""
website: ""
soft-depend: [Skript]
commands:
  bungeemaster:
    permission: bungeemaster.admin
    usage: "/<command> [reload|reconnect]"
    aliases: [bm, bmaster]