name: BungeeMaster
main: me.tonymaster21.bungeemaster.spigot.BungeeMaster
version: @VERSION@
authors: [TonyMaster21, xXAndrew28Xx]
description: Communicate with your Bungeecord instance!
website: https://bm.tonymaster21.me/
soft-depend: [Skript]
commands:
  bungeemaster:
    permission: bungeemaster.admin
    usage: "/<command> [reload|reconnect|dump]"
    aliases: [bm, bmaster]